default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: dbonilla
  password: basicdev

development:
  <<: *default
  database: bvapi

test:
  <<: *default
  database: bvapi_test

production:
  url: <%= ENV['DATABASE_URL'] %>
